### ISSUE TITLE
Discuss numeric stability of step where score statistic numerator is calculated

### ISSUE THREAD

**Issue by mir-cat** [mir-cat/BST234-FP#3]
Residuals can be negative, and so we run into the issue that subtraction of similar sized numbers can be unstable. Is there a way can avoid this in the code? Will it be too much of a speed loss to account for it? At the very least it should be discussed.

**Comment by katcorr** [comment]
I don't think it can be avoided, but yes we should discuss it.  Following along Note set 7, slides 18 - 23 ... 
We have y_i - p_i, since y_i = 0,1 and p_i in [0,1], then y_i - p_i is in [-1,1] and there is no upper bound as a function of eps (slide 23): the numerical error is <= 2 * eps * max{abs{y_i/(y_i- p_i)}, abs{p_i/(y_i-p_i)}, which can blow up when p_i is approx. y_i (which, ironically, is what we'd like it to be for good model fit).  

Question: Can 0 and 1 be represented exactly in binary floating point format?  I'm just thinking if the computer stores those exactly, it could help to cut down on the numerical error to <= eps*abs{p_i/(y_i-p_i)}, but perhaps that doesn't help much anyways...

The same thing comes up with the (1-p_i) in the denominator calculation if p_i is close to 1...

**Comment by katcorr** [comment]
Actually, instead of calculating SUM(y_i - p_i), maybe it would be more stable to calculate SUM(y_i) - SUM(p_i); that is, perform the summations of relevant y's (all > 0 so no stability issues there); then perform the summation of relevant p's  (all > 0 so no stability issues there).  Then perform the subtraction.  The thought here being that the sum of y_i's and the sum of p_i's will be LESS likely to be close to each other as compared to the individual y's and p's (also it's just one subtraction; versus m subtractions)...

**Comment by mir-cat** [comment]
The y_i are in {0,1,2}. We would have to do a check that doubles the y_I and p_i where x_i ==2. But multiplication is a safe operation so I can add that in.

**Comment by katcorr** [comment]
Y is the outcome and it is dichotomous, so y_i is only 0 or 1 (not 2).  X (the exposure) can be 0,1,2....  

For example of second way to calculate (summations separated):
# calculate observed score statistic 
ones <- which(proj.data$X_1 ==1)
twos <- which(proj.data$X_1 ==2)

y.ones <- proj.data$Y[ones]
p.ones <- proj.data$p[ones]
y.twos <- proj.data$Y[twos]
p.twos <- proj.data$p[twos]
observed.score.num <- (sum(y.ones) - sum(p.ones) + 2*sum(y.twos) - 2*sum(p.twos))^2
observed.score.denom <- sum(p.ones) - sum(p.ones^2) + 4*sum(p.twos) - 4*sum(p.twos^2)
observed.score <- observed.score.num/observed.score.denom

**Comment by mir-cat** [comment]
I will test this, but I think that the linear algebra routines in numpy are much faster than this method using multiple sums ind indexing operations. It may be a trade off between speed and stability.
